# Generated by Django 3.2.4 on 2023-09-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headlines', models.TextField()),
                ('slider_dec', models.TextField()),
                ('slider_picture', models.ImageField(null=True, upload_to='static/slider/')),
            ],
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='name',
        ),
        migrations.AddField(
            model_name='contactus',
            name='Name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
