# Generated by Django 3.2.4 on 2023-09-14 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_vnews_vlink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vnews',
            old_name='newdate',
            new_name='newsdate',
        ),
    ]
