# Generated by Django 3.2.4 on 2023-09-14 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_newdate_vnews_newsdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vnews',
            name='newsdate',
        ),
    ]
