# Generated by Django 3.2.4 on 2023-09-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_vnews_newsdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_picture',
            field=models.ImageField(null=True, upload_to='static/category/'),
        ),
    ]
