# Generated by Django 3.2.4 on 2023-09-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='vnews',
            name='newsdate',
            field=models.DateField(null=True),
        ),
    ]
